// Code generated by burrow build (Go target) -- VS0-for-Go v0, DO NOT EDIT.

package burrowgen

func OnGfdMobDeathXpBonusPercent(is_nm int32) int32 {
	return func() any {
		if is_nm >= 1 {
			return int32(50)
		}
		return int32(0)
	}().(int32)
}
