#!/usr/bin/env python3
"""Generate a dense but traversable expansion layout for the town scene."""
from __future__ import annotations

import argparse
from pathlib import Path


def hash32(n: int) -> int:
    n = (n ^ 61) ^ (n >> 16)
    n = n + (n << 3)
    n = n ^ (n >> 4)
    n = (n * 0x27D4EB2D) & 0xFFFFFFFF
    n = n ^ (n >> 15)
    return n & 0xFFFFFFFF


def pick(seed: int, lo: float, hi: float) -> float:
    v = hash32(seed) / 0xFFFFFFFF
    return lo + (hi - lo) * v


def emit_layout(path: Path, *, blocks_x: int, blocks_z: int, spacing: float, margin: float, origin_x: float, origin_z: float) -> int:
    out = []
    out.append("/* Auto-generated by tools/world/generate_town_expansion.py */")
    out.append("/* clang-format off */")
    out.append("static const TownBuildingSeed g_expansion_seed_buildings[] = {")

    idx = 0
    for bz in range(blocks_z):
        for bx in range(blocks_x):
            cx = origin_x + bx * spacing
            cz = origin_z + bz * spacing

            if (bx % 5 == 0) or (bz % 4 == 0):
                continue

            pattern = hash32((bx + 11) * 31337 + (bz + 7) * 92821) % 3
            offsets = [(-0.26, -0.24), (0.24, -0.22), (-0.20, 0.24), (0.20, 0.20)]
            if pattern == 1:
                offsets = [(-0.28, 0.0), (0.0, -0.26), (0.28, 0.0), (0.0, 0.26)]
            elif pattern == 2:
                offsets = [(-0.23, -0.23), (0.23, -0.23), (0.0, 0.25)]

            block_count = 0
            for ox, oz in offsets:
                seed = (bx + 1) * 1000003 + (bz + 1) * 9176 + block_count * 193
                w = pick(seed + 1, 10.0, 18.0)
                d = pick(seed + 2, 10.0, 18.0)
                h = pick(seed + 3, 14.0, 36.0)
                px = cx + ox * spacing
                pz = cz + oz * spacing

                if abs(ox) > 0.24 and pattern != 1:
                    w = min(w, spacing * (0.24 - margin))
                if abs(oz) > 0.24 and pattern != 1:
                    d = min(d, spacing * (0.24 - margin))

                out.append(
                    '    {BLD_MISC_COUNT, "Block %03d", %.2ff, %.2ff, %.2ff, %.2ff, %.2ff, 0},'
                    % (idx + 1, px, pz, w, d, h)
                )
                idx += 1
                block_count += 1

    out.append("};")
    out.append("/* clang-format on */")
    out.append("")
    path.write_text("\n".join(out), encoding="utf-8")
    return idx


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate town expansion seeds")
    parser.add_argument("--out", type=Path, default=Path("packages/world/generated/town_expansion_blocks.inl"))
    parser.add_argument("--blocks-x", type=int, default=20)
    parser.add_argument("--blocks-z", type=int, default=18)
    parser.add_argument("--spacing", type=float, default=34.0)
    parser.add_argument("--margin", type=float, default=0.04)
    parser.add_argument("--origin-x", type=float, default=-170.0)
    parser.add_argument("--origin-z", type=float, default=-130.0)
    args = parser.parse_args()

    count = emit_layout(
        args.out,
        blocks_x=args.blocks_x,
        blocks_z=args.blocks_z,
        spacing=args.spacing,
        margin=args.margin,
        origin_x=args.origin_x,
        origin_z=args.origin_z,
    )
    print(f"Generated {count} expansion buildings -> {args.out}")


if __name__ == "__main__":
    main()
