/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_abraham_fireball_cast(int, int, int);

void on_abraham_fireball_cast(int hero_index __attribute__((unused)), int target_x __attribute__((unused)), int target_z __attribute__((unused))) {
    redgarden_host_abraham_fireball_cast(hero_index, target_x, target_z);
}

