/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int blm_ability_for_slot(int);
int war_ability_for_slot(int);
int mnk_ability_for_slot(int);
int whm_ability_for_slot(int);
int rdm_ability_for_slot(int);
int thf_ability_for_slot(int);
int smn_ability_for_slot(int);
int on_gfd_ability_for_slot(int, int);

int blm_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 0)) {
    return 2;
    } else {
    if ((slot == 1)) {
    return 3;
    } else {
    if ((slot == 2)) {
    return 4;
    } else {
    return 0;
    }
    }
    }
}

int war_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 5;
    } else {
    if ((slot == 2)) {
    return 6;
    } else {
    return 0;
    }
    }
}

int mnk_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 7;
    } else {
    if ((slot == 2)) {
    return 8;
    } else {
    return 0;
    }
    }
}

int whm_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 9;
    } else {
    if ((slot == 2)) {
    return 10;
    } else {
    return 0;
    }
    }
}

int rdm_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 11;
    } else {
    if ((slot == 2)) {
    return 12;
    } else {
    if ((slot == 3)) {
    return 13;
    } else {
    if ((slot == 4)) {
    return 14;
    } else {
    if ((slot == 5)) {
    return 15;
    } else {
    return 0;
    }
    }
    }
    }
    }
}

int thf_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 16;
    } else {
    if ((slot == 2)) {
    return 17;
    } else {
    return 0;
    }
    }
}

int smn_ability_for_slot(int slot __attribute__((unused))) {
    if ((slot == 1)) {
    return 18;
    } else {
    if ((slot == 2)) {
    return 19;
    } else {
    return 0;
    }
    }
}

int on_gfd_ability_for_slot(int job __attribute__((unused)), int slot __attribute__((unused))) {
    if ((job == 3)) {
    return blm_ability_for_slot(slot);
    } else {
    if ((slot == 0)) {
    return 1;
    } else {
    if ((job == 0)) {
    return war_ability_for_slot(slot);
    } else {
    if ((job == 1)) {
    return mnk_ability_for_slot(slot);
    } else {
    if ((job == 2)) {
    return whm_ability_for_slot(slot);
    } else {
    if ((job == 4)) {
    return rdm_ability_for_slot(slot);
    } else {
    if ((job == 5)) {
    return thf_ability_for_slot(slot);
    } else {
    if ((job == 6)) {
    return smn_ability_for_slot(slot);
    } else {
    return 0;
    }
    }
    }
    }
    }
    }
    }
    }
}

