/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_apply_build_template_item(int, int);

int on_apply_build_template_item(int hero_index __attribute__((unused)), int item_id __attribute__((unused))) {
    return (redgarden_host_buy_build_item(hero_index, item_id));
}

