/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_duck_smoke_bomb_cast(int);

void on_duck_smoke_bomb_cast(int hero_index __attribute__((unused))) {
    redgarden_host_duck_smoke_bomb_cast(hero_index);
}

