/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_generate_counter_item(int, int, int);

int on_generate_counter_item(int base_item_a __attribute__((unused)), int base_item_b __attribute__((unused)), int slot_index __attribute__((unused))) {
    return (redgarden_host_item_curriculum_generate_counter_item(base_item_a, base_item_b, slot_index));
}

