/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_tree_passive_strike(int, int);

void on_tree_passive_strike(int hero_index __attribute__((unused)), int obstacle_index __attribute__((unused))) {
    redgarden_host_tree_passive_strike(hero_index, obstacle_index);
}

