// Package enmity implements the DragonsNShit hate / enmity system.
//
// # Enmity model (FFXI-parity)
//
// Every mob maintains an enmity table — a map from player slot to an integer
// enmity score. The mob always targets the player with the highest enmity
// ("Top() slot"). Enmity is generated by:
//   - Dealing damage (Cumulative Enmity: 1 CE per HP of damage)
//   - Casting heals (healer gains CE proportional to HP healed; AoE heals split CE)
//   - Overaggro (Volatile Enmity spikes — not tracked here; extension point)
//
// Enmity is capped at EnmityCap (default 10,000) per player per mob.
// Enmity cannot go below 0.
// On mob death all enmity should be cleared via Clear().
package enmity

import "errors"

const (
	EnmityCap = 10_000 // max enmity any single player can accumulate

	// FFXI CE ratios
	DamageEnmityRatio = 1    // 1 CE per HP of damage
	CureEnmityRatio   = 1    // 1 CE per HP of heal (single-target)
	AoECureDivisor    = 2    // AoE heal CE is halved vs single-target
)

var (
	ErrNoPlayers     = errors.New("no players on enmity table")
	ErrUnknownPlayer = errors.New("player slot not on enmity table")
)

// Table holds the enmity scores for a single mob.
// Not goroutine-safe; callers synchronise via the server tick loop.
type Table struct {
	scores map[string]int // slot → enmity
}

// NewTable returns an empty enmity table.
func NewTable() *Table {
	return &Table{scores: make(map[string]int)}
}

// Ensure creates an entry for slot at 0 enmity if not already present.
// Call this whenever a player first engages a mob (tags it with an attack).
func (t *Table) Ensure(slot string) {
	if _, ok := t.scores[slot]; !ok {
		t.scores[slot] = 0
	}
}

// Add adds damage-based CE for slot (1 CE per HP of damage dealt).
// Clamps to [0, EnmityCap].
// Registers slot if not already tracked.
func (t *Table) Add(slot string, damage int) {
	t.Ensure(slot)
	t.scores[slot] = clamp(t.scores[slot]+damage*DamageEnmityRatio, 0, EnmityCap)
}

// AddCure adds heal-based CE for healer slot.
// AoE heals generate half the CE of single-target heals.
// Registers slot if not already tracked.
func (t *Table) AddCure(slot string, healing int, isAoE bool) {
	t.Ensure(slot)
	ce := healing * CureEnmityRatio
	if isAoE {
		ce = ce / AoECureDivisor
	}
	t.scores[slot] = clamp(t.scores[slot]+ce, 0, EnmityCap)
}

// Reduce removes enmity from slot (e.g. from Enmity Douse effects).
// Clamps at 0. No-op if slot is not on table.
func (t *Table) Reduce(slot string, amount int) {
	if _, ok := t.scores[slot]; !ok {
		return
	}
	t.scores[slot] = clamp(t.scores[slot]-amount, 0, EnmityCap)
}

// Top returns the slot with the highest enmity score.
// On tie, returns the slot that sorted first alphabetically (deterministic).
// Returns ("", ErrNoPlayers) if the table is empty.
func (t *Table) Top() (string, error) {
	if len(t.scores) == 0 {
		return "", ErrNoPlayers
	}
	best := ""
	bestScore := -1
	for slot, score := range t.scores {
		if score > bestScore || (score == bestScore && (best == "" || slot < best)) {
			bestScore = score
			best = slot
		}
	}
	return best, nil
}

// Score returns the current enmity for slot.
// Returns 0 and ErrUnknownPlayer if slot is not tracked.
func (t *Table) Score(slot string) (int, error) {
	s, ok := t.scores[slot]
	if !ok {
		return 0, ErrUnknownPlayer
	}
	return s, nil
}

// Clear removes all enmity (call on mob death or reset).
func (t *Table) Clear() {
	for k := range t.scores {
		delete(t.scores, k)
	}
}

// Remove removes a specific slot (player left zone, died, etc.).
func (t *Table) Remove(slot string) { delete(t.scores, slot) }

// Len returns how many players are currently tracked.
func (t *Table) Len() int { return len(t.scores) }

// Slots returns a snapshot of all tracked slots (order unspecified).
func (t *Table) Slots() []string {
	out := make([]string, 0, len(t.scores))
	for k := range t.scores {
		out = append(out, k)
	}
	return out
}

func clamp(v, lo, hi int) int {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}
